### ISSUE TITLE
Making subtitle class JSON serializable

### ISSUE THREAD

**Issue by govindjoshi12** [dusking/opensubtitles-com#9]
I want to make a small change to the repository which would allow dumping response dictionaries as json.

The change would consist of adding the following class to responses.py

```
class SubtitleJSONEncoder(json.JSONEncoder):

    def default(self, o: object) -> Any:
        if isinstance(o, Subtitle):
            return o.__dict__
        return super().default(o)
```

And it can be used in the following way

```
from opensubtitlescom.responses import SubtitleJSONEncoder

response = subtitles.search(query="breaking bad", episode_number=1, season_number=1, languages="en")
response_dict = response.to_dict()

json.dumps(response_dict, cls=SubtitleJSONEncoder)
```
This is useful because the response dict consists of Subtitle objects. They can be printed without issue, but if they need to be served from an api endpoint, it is necessary to convert them into json.

**Comment by dusking** [comment]
Thank you for your feedback. I've incorporated your suggestion and added a to_json method to the Response class. You can now use it as follows:

`response = subtitles.search(query="breaking bad", episode_number=1, season_number=1, languages="en")
response.to_json()`

I've also updated the README file to reflect this new functionality. If you have any more suggestions or questions, feel free to let me know!
